### PR TITLE
Added 'ratio' comment caused visibility flag to be ignored

### PR DESCRIPTION
**Pull request by nbonniere**
Comments moved as it caused a problem with the visibility flag setting to be ignored.

### CODE REVIEW

**Comment by acasadoalonso** [comment]
Nick,
Do you want to apply yourself this PR ???
Thx.

AC/.

**Comment by nbonniere** [comment]
Can you have a quick second look at the minor changes and if OK, you can proceed with the PR.

Nick

**Comment by acasadoalonso** [comment]
Will do.

AC/.

**Comment by acasadoalonso** [comment]
PR accepted and merged

**Pull request merged**
